apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  redis-host:          "{{ .Release.Name }}-redis-master"
  product-service-url: "http://product-service:8081"
  order-service-url:   "http://order-service:8082"
  user-service-url:    "http://user-service:8083"
  aws-region:          "ap-south-1"
  s3-bucket:           "ecommerce-assets-production"
