server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}

aws:
  region: ap-south-1
  sns:
    order-events-topic-arn: ${AWS_SNS_TOPIC_ARN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
